[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2977ae75bdbb446d5286028195f4f4dfc3e46299"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "84ef6b1a61d2846bea14eb01a24a5e6ef55b03061792754fda73e7b4bac56914"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "31cdfb27b34bca2c241121792c15873a42d133ad"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "099b9c402cdc26dd6327eba61adabfbc4d5ba752cb78a9de18d9047a617d8b73"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "81bf9cd9354d81830ab87667b71ed58e329abcef"
julia_version = "1.12.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "f863e50fce083f959f6e26eae406cb658b1c4fec91d3dfd260d2350af62a5c00"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.12.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "none"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e2e59228eee1b30af2f0fe5f5df06a29a124707"
julia_version = "1.13.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "ea9834c01e2fc39fa655d359d822f1b4a0fa89137515f8457694c28dd349acb8"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+none-julia_version+1.13.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "834c4d4034e7a1f4faa1fb0510f1d6d3e2c26c09"
julia_version = "1.10.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "36ef8cf94f2fe0cfc653658240ac1010ed29539140fb883622314fe3a69d072a"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.10.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "743b031927f55695121f1c1a35f3a2ede7e5362d"
julia_version = "1.11.1"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "ee53b3250df5f328c38a41d5bfcfd8b16a8def75530da43acc50f526493c3497"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.11.1.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8415099f3f6f42f66273f1e4f04a19e4c8515e4d"
julia_version = "1.12.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "9c5df043188ccceff28a4ef6a39261d9af86a3cb2019703a906cf7bf5c29b53d"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.12.0.tar.gz"
[[cunumeric_jl_wrapper]]
arch = "x86_64"
cuda = "13.0"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9631ea5ecd315690356a79d8c535bcc081e29e3d"
julia_version = "1.13.0"
lazy = true
libc = "glibc"
os = "linux"

    [[cunumeric_jl_wrapper.download]]
    sha256 = "fada2cb7da3f40562a394e1347bbf947b22622f5b1e00c3b3b8359dd38288c7e"
    url = "https://github.com/JuliaBinaryWrappers/cunumeric_jl_wrapper_jll.jl/releases/download/cunumeric_jl_wrapper-v26.6.3+0/cunumeric_jl_wrapper.v26.6.3.x86_64-linux-gnu-cxx11-cuda+13.0-julia_version+1.13.0.tar.gz"
