# Autogenerated wrapper script for cunumeric_jl_wrapper_jll for x86_64-linux-gnu-cxx11-cuda+12.6-julia_version+1.11.1
export libcunumeric_c_wrapper, libcunumeric_jl_wrapper

using cupynumeric_jll
using legate_jll
using libcxxwrap_julia_jll
using CompilerSupportLibraries_jll
using CUDA_Runtime_jll
JLLWrappers.@generate_wrapper_header("cunumeric_jl_wrapper")
JLLWrappers.@declare_library_product(libcunumeric_c_wrapper, "libcunumeric_c_wrapper.so.0.0.1")
JLLWrappers.@declare_library_product(libcunumeric_jl_wrapper, "libcunumeric_jl_wrapper.so.0.0.1")
function __init__()
    JLLWrappers.@generate_init_header(cupynumeric_jll, legate_jll, libcxxwrap_julia_jll, CompilerSupportLibraries_jll, CUDA_Runtime_jll)
    JLLWrappers.@init_library_product(
        libcunumeric_c_wrapper,
        "lib/libcunumeric_c_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libcunumeric_jl_wrapper,
        "lib/libcunumeric_jl_wrapper.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
